/*
 * This file is generated by jOOQ.
 */
package gensrc;


import gensrc.tables.RoleMaster;
import gensrc.tables.UserMaster;
import gensrc.tables.records.RoleMasterRecord;
import gensrc.tables.records.UserMasterRecord;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code></code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<UserMasterRecord, Integer> IDENTITY_USER_MASTER = Identities0.IDENTITY_USER_MASTER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<RoleMasterRecord> CONSTRAINT_4 = UniqueKeys0.CONSTRAINT_4;
    public static final UniqueKey<UserMasterRecord> CONSTRAINT_8 = UniqueKeys0.CONSTRAINT_8;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<UserMasterRecord, RoleMasterRecord> CONSTRAINT_8E = ForeignKeys0.CONSTRAINT_8E;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<UserMasterRecord, Integer> IDENTITY_USER_MASTER = Internal.createIdentity(UserMaster.USER_MASTER, UserMaster.USER_MASTER.USER_ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<RoleMasterRecord> CONSTRAINT_4 = Internal.createUniqueKey(RoleMaster.ROLE_MASTER, "CONSTRAINT_4", new TableField[] { RoleMaster.ROLE_MASTER.ROLE_ID }, true);
        public static final UniqueKey<UserMasterRecord> CONSTRAINT_8 = Internal.createUniqueKey(UserMaster.USER_MASTER, "CONSTRAINT_8", new TableField[] { UserMaster.USER_MASTER.USER_ID }, true);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<UserMasterRecord, RoleMasterRecord> CONSTRAINT_8E = Internal.createForeignKey(Keys.CONSTRAINT_4, UserMaster.USER_MASTER, "CONSTRAINT_8E", new TableField[] { UserMaster.USER_MASTER.ROLE_ID }, true);
    }
}
